# This workflow will install Python dependencies, run tests and lint with a variety of Python versions


name: Bikeshare

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7","3.8","3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        make install
    - name: test with pytest
      run: |
        make test    
    - name: Verify model is built
      run: |
        make train
    - name: Lint with pylint
      run: |
        make lint
    - name: Verify the built pkl file this time
      run: |
        make test
